---
version: '3'

services:
  hydra2:
    image: linuxserver/hydra2
    volumes:
      - '${CONFIG}/hydra2:/config'
      - '${DOWNLOADS}/watched:/downloads'
    ports:
      - 5076:5076
  jackett:
    image: linuxserver/jackett
    volumes:
      - '${CONFIG}/jackett:/config'
      - '${DOWNLOADS}/watched:/downloads'
    ports:
      - 9117:9117
  sonarr:
    image: linuxserver/sonarr:latest
    volumes:
      - '${CONFIG}/sonarr:/config'
      - '${MEDIA}/tv:/tv'
      - '${DOWNLOADS}/completed/tv/downloads'
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr:latest
    volumes:
      - '${CONFIG}/radarr:/config'
      - '${MEDIA}/movies:/movies'
      - '${DOWNLOADS}/completed/movies:/downloads'
    ports:
      - 7878:7878
  lidarr:
    image: linuxserver/lidarr:latest
    volumes:
      - '${CONFIG}/lidarr:/config'
      - '${MEDIA}/music:/music'
      - '${DOWNLOADS}/completed/music:/downloads'
  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    volumes:
      - '${CONFIG}/lazylibrarian:/config'
      - '${MEDIA}/books:/books'
      - '${DOWNLOADS}/completed/books:/downloads'
    ports:
      - 5299:5299
  ombi:
    image: linuxserver/ombi:latest
    volumes:
      - '${CONFIG}/ombi:/config'
    ports:
      - 3579:3579
  sabnzbd:
    image: lsioarmhf/sabnzbd
    volumes:
      - '${CONFIG}/sabnzdb:/config'
      - '${DOWNLOADS}:/downloads'
      - '${DOWNLOADS}/incomplete:/incomplete-downloads'
    ports:
      - 8080:8080
      - 9090:9090
  rutorrent:
    image: linuxserver/rutorrent
    volumes:
      - "${CONFIG}/rutorrent:/config"
      - "${DOWNLOADS}:/downloads"
    ports:
      - 6881:6881/udp
      - 51413:51413
      - 5000:5000
      - 84:80
